/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ice_caster_android_shout_Lame */

#ifndef _Included_ice_caster_android_shout_Lame
#define _Included_ice_caster_android_shout_Lame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ice_caster_android_shout_Lame
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_ice_caster_android_shout_Lame_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     ice_caster_android_shout_Lame
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_ice_caster_android_shout_Lame_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     ice_caster_android_shout_Lame
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_ice_caster_android_shout_Lame_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     ice_caster_android_shout_Lame
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ice_caster_android_shout_Lame_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
